---
AWSTemplateFormatVersion: '2010-09-09'
Description: Calligre DynamoDB CF Stack
Resources:
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: calligre-posts
      AttributeDefinitions:
      - AttributeName: posts
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: N
      KeySchema:
      - AttributeName: posts
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
  FlaggedPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flagged
      AttributeDefinitions:
      - AttributeName: timestamp
        AttributeType: N
      KeySchema:
      - AttributeName: timestamp
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
  PostsTableReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '5'
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Period: '60'
      Statistic: Sum
      Threshold: '240.0'
      AlarmActions:
      - Ref: AlertSnsTopic
      Dimensions:
      - Name: TableName
        Value:
          Ref: PostsTable
  PostsTableWriteCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '5'
      MetricName: ConsumedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Period: '60'
      Statistic: Sum
      Threshold: '240.0'
      AlarmActions:
      - Ref: AlertSnsTopic
      Dimensions:
      - Name: TableName
        Value:
          Ref: PostsTable
  FlaggedPostsTableReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '5'
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Period: '60'
      Statistic: Sum
      Threshold: '240.0'
      AlarmActions:
      - Ref: AlertSnsTopic
      Dimensions:
      - Name: TableName
        Value:
          Ref: FlaggedPostsTable
  FlaggedPostsTableWriteCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '5'
      MetricName: ConsumedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Period: '60'
      Statistic: Sum
      Threshold: '240.0'
      AlarmActions:
      - Ref: AlertSnsTopic
      Dimensions:
      - Name: TableName
        Value:
          Ref: FlaggedPostsTable
  AlertSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: DynamoDB Alarms
  AlertSnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
      - Ref: AlertSnsTopic
      PolicyDocument:
        Version: '2008-10-17'
        Id: __default_policy_ID
        Statement:
        - Sid: __default_statement_ID
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource:
            Ref: AlertSnsTopic
          Condition:
            StringEquals:
              AWS:SourceOwner: 037954390517
